### PR TITLE
[#42] Add fix for error 422 [The message submitted is longer that the ma...

### LINKED ISSUE #42: Restrict github status api descriptions to 140 characters
Otherwise we get a 422 error from github

### PR DESCRIPTION
**Pull request by davecaos**
Fix #42

### CODE REVIEW

File: src/egithub.erl [hunk 1]
```diff
@@ -480,6 +481,17 @@ combined_status(Cred, Repo, Ref) ->
 %% Private Functions
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 
+%doc format_description format the description to avoid error 422
+%doc The message submitted is longer that the maximum length of 140 characters
+-spec format_description(string()) -> string().
+format_description(Description) ->
+  MaxLengthDescrip = 140,
```
Comment (elbrujohalcon) [inline src/egithub.erl]: put this in a macro

File: src/egithub.erl [hunk 2]
```diff
@@ -480,6 +481,17 @@ combined_status(Cred, Repo, Ref) ->
...
+  case length(Description) of
+    Size when Size >= MaxLengthDescrip -> 
+      string:sub_string(Description, 1, 137) ++ "..."; %% to be continued.
```
Comment (elbrujohalcon) [inline src/egithub.erl]: replace `137` by `?MAX_DESCRIPTION_LENGTH - 3`
