### PR TITLE
[#46] Add erlang:get_stacktrace() to search errors in event() call

### LINKED ISSUE #46: Set stack erlang:get_stacktrace() to search error in events
This issue it is linked to https://github.com/inaka/elvis/issues/234

### PR DESCRIPTION
**Pull request by davecaos**
Fix #46 and This issue it is linked to inaka/elvis#234

### CODE REVIEW

File: src/egithub_webhook.erl [hunk 1]
```diff
@@ -68,6 +68,10 @@ event(Module, StatusCred, ToolName, Context, CommentsCred, Request) ->
           {error, Error}
       catch
         _:Error ->
+          lager:warning(
+            "event:Error ~p Module: ~p ToolName: ~p "
+            ++ "Context: ~p EventData: ~p get_stacktrace: ~p",
+            [Error, Module, ToolName, Context, EventData, erlang:get_stacktrace()]),
```
Comment (gadgetci) [inline src/egithub_webhook.erl]: According to **Elvis**:
> Line 74 is too long:             [Error, Module, ToolName, Context, EventData, erlang:get_stacktrace()]),.
