### PR TITLE
[Fix #115] Fix wrong specs according to dialyzer@r19.0.5

### LINKED ISSUE #115: Wrong spec for request() type on egithub_webhook module
The [spec](https://github.com/inaka/erlang-github/blob/master/src/egithub_webhook.erl#L15) for this type says that `request` is a map with a `body` key whose value is a map:

```erlang
-type request() :: #{headers => map(), body => map()}.
```

Then on [line 47](https://github.com/inaka/erlang-github/blob/master/src/egithub_webhook.erl#L47) the code expects this value to be a binary:

```erlang
EventData = egithub_json:decode(Body),
```

### PR DESCRIPTION
**Pull request by harenson**

### CODE REVIEW

File: src/egithub_webhook.erl [hunk 1]
```diff
@@ -12,7 +12,7 @@
 
 -export_type([request/0]).
 
--type request() :: #{headers => map(), body => map()}.
+-type request() :: #{headers => map(), body => binary()}.
```
Comment (HernanRivasAcosta) [inline src/egithub_webhook.erl]: Not a fan of this. I do think we should do our best to ensure the decode function is called only once.
